### ISSUE TITLE
希望增加一个数量限制

### ISSUE THREAD

**Issue by vjieshao** [AwesomeDennis/DXPhotoPicker#1]
选择照片时不能设定只选多少张照片。

**Comment by dennisxiaoding** [comment]
@vjieshao 可以的啊 在`DXPhotoBrowser` 中的 `DXPhotoBrowserConfig` 有个`maxSeletedNumber`你可以修改这个值。别忘了在 `DXPhotoPicker.strings`文件里修改

**Comment by vjieshao** [comment]
OK。好得，谢谢了。用起来还不错，要是能提供个接口出来就好了。之前用过一个是有接口的。

**Comment by vjieshao** [comment]
如果我有个需求，一共限定9张图片，第一次进来我选中了6张，下次进来就要限定用户只能选定3张了，如果用你这个框架怎么用代码动态改变这个限定值呢？

**Comment by dennisxiaoding** [comment]
@vjieshao 当前来说是不可以的，但是你可以写一个你的manager，来管理你的逻辑。然后吧maxSeletedNumber 改成可以动态传递的
